### ISSUE TITLE
SOMEBODY JUST ASSUMED MY GENDER 😱

### ISSUE THREAD

**Issue by bash** [SirRade/shootr#41]
HELP ME I'M SO OFFENDED!!!!!
OH MY GOD THERE ARE PEOPLE WITH DIFFERENT OPINIONS I FEEL VIOLATED!!!

**Comment by SirRade** [comment]
Hello Ruben

Wow, that is unfortunate! 
Howevermuch we are conserned about this atrocity (rest assured that our prayers 🙏 are with you), I feel like this projects ambitions and possibilities are limited in the way they might assist in your favour.

**Comment by bash** [comment]
YOU CISGENDER WHITE MALES JUST DONT GET IT!!!!

**Comment by SirRade** [comment]
might be related to https://github.com/SirRade/shootr/issues/42

**Comment by SirRade** [comment]
Dear Ruben

Our research team has come up with some detailed information about your recent inquiry: https://howmanygendersexist.com/

In order to resolve this matter, please mark which gender identity you agree more on, so we are no longer required to proceed in any "assuming" anymore:

- [ ] Male 👨 
- [ ] Female 👩

**Comment by bash** [comment]
You forgot to mention the following gender:

- [x] Unicorn pooping Rainbow 🦄💩🌈

**Comment by SirRade** [comment]
This will require some refactoring of our webscale mongodb, but we can do it.
